//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : OPRoS Component
//  @ File Name : Acceptor.cpp
//  @ Date : 2008-08-22
//  @ Author :
//
//


#include "IoAcceptor.h"

#include "system/SystemTypes.h"

using namespace std;

IoConnection *IoAcceptor::detachConnection(const string &cnnId)
{
	IoEventTarget *obj = detachEventTarget(cnnId);
	if (obj != NULL) {
		return portable_dynamic_cast(IoConnection *, obj);
	}

	return NULL;
}

bool IoAcceptor::attachConnection(IoConnection *cnn)
{
	return attachEventTarget(cnn);
}
